language: node_js
node_js:
- "8"
jobs:
  include:
  - stage: test1
    script:
    - echo success
notifications:
  webhooks:
    - http://106.10.59.172/webhook
    - http://2a858171.ngrok.io/webhookhandler/github
