language: node_js
node_js:
- "8"
jobs:
  include:
  - stage: test1
    script:
    - echo success
notifications:
  webhooks:
    urls:
      - http://106.10.59.172/webhook
      - https://43d4da8e.ngrok.io/webhookhandler/travisci
    on_start:   always
    on_success: always
    on_failure: always
